- frontend/src/component/NavLink.js
- frontend/src/component/Navbar.js
- frontend/src/index.html
- frontend/src/index.js
- frontend/src/pages/Login.js
- frontend/src/pages/Main.js
- frontend/src/pages/Profile.js
- frontend/src/scss/colors.scss
- frontend/src/scss/styles.scss
- #8 
- 메인 페이지 스타일 적용
- NavLink 함수형 컴포넌트로 구현
- 라우팅할 때 사용하는 경우가 많아 a태그로 구현
- text, path, 클래스 리스트를 받아서 적용
- 클래스 디폴트값은 부트스트랩 네비게이션바에서 쓰는 'nav-link'
- 기본 색상들 변수명 지정해서 colors.scss로 작성
- 화면이 작아지면 난리가 나는데 body에 min-width 지정해줘도 안되네요.. 혹시 방법을 아신다면 적용 부탁드립니다
> [Feat] 메인 페이지 레이아웃

- frontend/src/component/navigation/NavBar.js
- frontend/src/component/navigation/NavLink.js
- frontend/src/index.js
- frontend/src/pages/Home.js
- frontend/src/pages/game/CreateRoom.js
- frontend/src/pages/game/Game.js
- frontend/src/pages/game/JoinRoom.js
- frontend/src/scss/styles.scss
- close #28 
- 게임 메인 페이지 레이아웃 구현했습니다
- NavLink classList 배열에서 문자열로 수정했습니다
-
> [Design] 대기실 화면 레이아웃

- frontend/src/component/button/LoginPageButtons.js
- frontend/src/component/form/RegisterForm.js
- frontend/src/component/modal/ModalComponent.js
- frontend/src/constants/Regex.js
- frontend/src/pages/Login.js
- #23 
- nickname 정규식 추가했습니다.
- login 토스트 그대로 사용했습니다.
- api 연결 후 에러처리나 리퀘스트 바디 명세에 맞게 수정하겠습니다.
- 현재는 연결해두신 json-server db에 등록됩니다.
- 로그인 페이지에 요청 핸들러와 연관 로직들이 많아서 이걸 분리해야 할지 그대로 사용할지 의견 궁금합니다.
> [FEAT] 회원가입 기능

- frontend/db.json
- frontend/src/component/button/BasicButton.js
- frontend/src/component/button/FriendPageButtons.js
- frontend/src/component/contents/FriendSearch.js
- frontend/src/component/contents/FriendSearchListItem.js
- frontend/src/component/contents/FriendWaitList.js
- frontend/src/component/contents/FriendWaitListItem.js
- frontend/src/pages/Friends.js
- frontend/src/scss/styles.scss
- frontend/src/utils/debounce.js
- #24 
- 친구 대기 리스트 모달
- 친구 목록 불러오기
- 친구 추가 모달
- 친구 검색
- 친구 추가
---
- 친구 검색에 디바운스 적용해서 1초마다 자동 검색하도록 했습니다.
- 대기리스트와 검색리스트 아이템들은 다 동적으로 생성되고 해당 아이템 내부 버튼에 이벤트가 친구 닉네임에 맞춰 다르게 들어가야 추가돼야 해서 해당 컴포넌트들은 템플릿 리터럴 형식에서 돔요소를 직접 생성하고 이벤트를 붙이는 방식으로 변경했습니다.
- Friend페이지에서 모달 내부에서 동적으로 생성되는 버튼 로직까지 다 관리하는 것도 애매하고, 구현 및 관리도 더 편해서 변경했습니다.
- 모달 닫힐 때 input 내용이나 get 요청으로 불러온 데이터로 생성된 돔 요소들 삭제하게 했습니다.
- api 세부 로직은 연결 후 추가하겠습니다.
- 검색 테스트는 json-server로 하는 거라 같은 값만 리턴합니다.
- styles 에서 삭제된 부분은 중복으로 들어간 부분이라 삭제했습니다.
-
> [Feat] 친구 모달 내부 기능

- Makefile
- docker-compose.yml
- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
- nginx/Dockerfile
- nginx/server.conf
- #41 
- ~~frontend에서 빌드된 결과물을 볼륨을 통해 nginx와 공유합니다.~~ 
- 나중에 빌드 결과물을 static 경로에 두고 nginx로 접근할 때 사용합니다.
- 지금 npm run dev로 실행한 3000번 포트로 보냅니다.
- compose 파일에 컨테이너명과 이미지명을 추가했습니다.
- makefile 추가했습니다.
- 아래 링크들 보고 따라했는데 맞게 한건지는 모르겠습니다..
- https://juhonamnam.github.io/5/
- https://velog.io/@bebop0303/local%EC%97%90%EC%84%9C-vite-nginx%EB%A5%BC-%EB%8F%84%EC%BB%A4-%EC%9D%B4%EB%AF%B8%EC%A7%80%EB%A1%9C-%EB%A7%8C%EB%93%A4%EC%96%B4-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0#3-dockerfile-%EC%83%9D%EC%84%B1
-
> [Feat] nginx 프론트 연결

- frontend/src/utils/router.js
- #33
- 로컬 스토리지에 이전 페이지 계속 저장해서 가져오는 방식 사용해봤는데 괜찮은지 모르겠습니다.
-
> [Fix] 로그인페이지 접근 제한

- frontend/src/component/button/BasicButton.js
- frontend/src/component/button/LoginPageButtons.js
- frontend/src/pages/game/JoinRoom.js
- frontend/src/scss/styles.scss
- #49 
- 클래스 충돌되는 문제때문에 기본 클래스 삭제했습니다
-
> [Fix] BasicButton 컴포넌트 스타일 수정

- backend/login/views.py
- docker-compose.yml
- nginx/server.conf
> Backend merge

- nginx/server.conf
- #53 
- backend 프록시 설정 추가했습니다
-
> [FIX] nginx config backend proxy 설정 추가

- backend/login/views.py
- backend/users/views.py
- 
- OAuth 심폐소생술
- OAuth callback view 반환값 변경 (JWT token -> redirect)
> [BE] Fix: oauth callback 반환값 변경

- backend/login/views.py
- 
- oauth, logout 수정
- oauth 시 이미 로그인 상태일 때에도 반환값 redirect로 변경
- logout 시 쿠키 삭제
> [Fix] oauth, logout 수정

- frontend/src/pages/Login.js
> [Fix] 이메일 인증 모달 수정

- frontend/src/pages/Login.js
- frontend/src/scss/styles.scss
- frontend/src/utils/Fetch.js
- frontend/src/utils/TokenManager.js
> [Fix] Fetch credentials 수정

- frontend/src/utils/TokenManager.js
- #70 
- reissueAccessToken 추가
-
> [Feat] reissueAccessToken 추가

- backend/login/utils.py
- backend/login/views.py
- 
- JWT cookie 조건 수정
- logout 정식 구현
-
> [Fix] JWT cookie 조건 수정, logout 정식 구현

- docker-compose.yml
- frontend/Dockerfile
- nginx/Dockerfile
- nginx/init.sh
- nginx/server.conf
- 
- nginx tls 설정
- 프론트 dev 서버가 http 로 돌아가고 있어서 build 해서 붙이는 방식으로 수정해놨습니다.
- 프론트 dev서버를 https로 바꾸고 nginx proxy에서 https://frontend:3000으로 바꾸면 502 에러가 나는데 뭐가 문제인지 모르겠어서 그냥 build해서 nginx가 해당파일 보여주도록 Dockerfile 수정했습니다.
- https://localhost로 접속됩니다
- 인셉션에서 사용했던 방식 그대로 가져다 쓴거라 맞게 적용한건지 잘 모르겠네요
> [Feat] nginx ssl/tls 추가

- backend/backend/settings.py
- backend/login/views.py
> [BE] Fix: refrest token view fix

- frontend/src/index.html
- frontend/src/index.js
- frontend/src/pages/Login.js
- frontend/src/scss/styles.scss
- frontend/src/utils/Fetch.js
- frontend/src/utils/TokenManager.js
- frontend/src/utils/router.js
- #84 
- `index.js` 에서 body 클릭 이벤트를 navBar 클릭 이벤트로 수정
- body 클릭 이벤트 안에 있던 로그아웃 버튼 이벤트 리스너 위치 수정
- 로그아웃 401에러 시에 토큰 재발급 요청 보내도록 Fetch 조건문 수정
- 로그아웃, 토큰 재발급 실패시 토큰 삭제
- 로딩 컴포넌트 구현 및 Fetch 시 로딩 처리
- 42로그인 시 뒤에 함수 실행 안하도록 return (navigate 해서 요소를 찾지 못하는 에러 발생하여 수정)
- 로딩 애니메이션은 일단 임시로 구현해보았는데 피드백 부탁드립니다
- 그리고 모든 로딩을 이렇게 전역으로 다 관리해도 괜찮을지 모르겠네요
> [Fix] 로그아웃 여러 번 요청하는 문제, 로딩 처리

- backend/backend/settings.py
- backend/backend/urls.py
- backend/friends/admin.py
- backend/friends/apps.py
- backend/friends/models.py
- backend/friends/serializers.py
- backend/friends/tests.py
- backend/friends/urls.py
- backend/friends/views.py
- backend/users/tests.py
- friend api 추가
- friend list
- waiting request
- add request
- friend apit test.py
-
> 78 feat profile friend api 구현

- backend/backend/settings.py
- backend/backend/urls.py
- backend/rooms/admin.py
- backend/rooms/apps.py
- backend/rooms/models.py
- backend/rooms/serializers.py
- backend/rooms/tests.py
- backend/rooms/urls.py
- backend/rooms/views.py
- backend/users/serializers.py
- room list api 구현
- create room view
- join room view
-
> 94 feat game rooms api

- backend/friends/urls.py
- backend/friends/views.py
> [BE] Fix: swagger error fix

- backend/friends/views.py
- backend/rooms/models.py
- backend/rooms/tests.py
- backend/rooms/urls.py
- backend/rooms/views.py
- backend/users/models.py
- room, friend api swagger 전면 수정
- room list api -> game mode 분리
- user is_active default True 변경
- 
-
> [BE] Fix: swagger fix, room api 분리

- .gitignore
> Chore: git ignore fix

- backend/friends/admin.py
- backend/rooms/admin.py
- backend/users/models.py
- create super user 매서드 추가
- admin계정에서 db관리 가능
- 
-
> [BE]Feat: create superuser method add

- backend/cmd.sh
- docker container 실행 시 admin계정 
- localhost:8000/admin에서 admin계정 사용 가능
-
> [BE]Chore: admin id add

- frontend/src/index.js
- frontend/src/utils/TokenManager.js
- #102 
- 최초 접속 시 유효한 유저인지 확인하기 위해 새로고침할 때마다 access token 재발급 요청을 보냅니다
- access token 로컬 스토리지 대신 변수에 저장하는 방식으로 수정했습니다
- 기존 코드는 혹시 모를 상황을 대비해 테스트용으로 일단 주석 처리 해두었습니다
- 리프레쉬 토큰이 없을 때(로그인 안 된 유저)는 토스트 띄우지 않고 유효하지 않은 리프레쉬 토큰 에러일 때만 토스트 띄웁니다
-
> [FIX] 새로고침할 때마다 토큰 재발급 요청

- frontend/src/component/PageComponent.js
- frontend/src/component/navigation/NavLink.js
- frontend/src/index.js
- frontend/src/pages/Home.js
- frontend/src/pages/game/Game.js
- #112 
- spa가 적용되지 않던 문제
- index.js에서 해당하는 a태그를 제대로 가져오지 못하던 문제
- DomContentLoaded가 처음 html이 로드될 때만 실행되기 때문에 페이지 렌더링 시 생성되는 navlink 버튼에는 해당 이벤트가 적용되지 않던 문제
- DomContentLoaded 시 모든 a태그를 불러와서 클릭이벤트를 적용해줍니다.
- PageComponent에 onNavButtonClick 메서드 추가해서, navlink가 들어간 페이지마다 afterRender에서 실행하도록 수정했습니다.
- navlink 들어갈 페이지에는 afterRender에 해당 메서드 추가해주시면 됩니다.
- onNavButtonClick에서는 이미 클릭이벤트가 적용된 menu의 a태그들은 불러오지 않도록 navlink의 데이터 링크를 가져와서 적용합니다.
-
> [Fix] spa 작동 안함

- frontend/src/pages/game/JoinRoom.js
- #101 
- join room api 연결
- 페이지네이션 대신 모든 데이터를 한 번에 받아와 스크롤로 보여줍니다
- `http://localhost:8000/admin` 에서 room db 추가하여 테스트도 가능합니다(아이디 비번 test로 동일)
-
> [Feat] join room api 연결

- backend/friends/views.py
- docker-compose.yml
- nginx/server.conf
- nginx volumn 추가
- friend api accept code 수정
- 
-
> Fix nignx volumn add

- frontend/src/component/contents/FriendSearchListItem.js
- frontend/src/component/contents/FriendWaitListItem.js
- frontend/src/pages/Friends.js
- #98
- 친구 검색, 친구 추가, 친구 수락, 친구 거절  api 연결입니다.
- 검색 후 친구 신청
- 친구 수락/ 거절 부분은 백엔드 수정 후에 다시 테스트 해보겠습니다.
- 수락/ 거절 후 다시 렌더링 하는 부분도 에러가 날 거 같은데 수정되면 다시 고치겠습니다.
-
> [Feat] 친구페이지 모달 api 연결

- backend/friends/models.py
- backend/friends/tests.py
- backend/friends/views.py
- backend/login/views.py
- backend/users/models.py
- friend model 수정
- intra login image default image로 수정
- 친구 추가시 상대방 친구목록에도 추가
- 중복 친구 추가 신청시 409 리턴
- 이미 친구 목록에 있을시 409 리턴
-
> 120 be fix friend api fix

- frontend/src/component/form/LoginForm.js
- frontend/src/component/form/RegisterFormItem.js
- frontend/src/pages/Friends.js
- frontend/src/pages/Home.js
- frontend/src/pages/Login.js
- frontend/src/pages/Profile.js
- frontend/src/scss/styles.scss
- frontend/src/utils/Fetch.js
- #119, #114 
- email, code 입력 시 폰트 스타일 대소문자 구분되도록 수정하였습니다
- 회원가입, 친구 검색, 프로필 편집 api 요청 시 username 소문자로 바꿔서 보내줍니다
- 로딩 컴포넌트 z-index 수정했습니다
-
> [Design] 입력받는 부분 폰트 수정, 로딩 버그 수정

- backend/users/tests.py
> [BE] Chore: black formatter 적용

- backend/login/views.py
- 
- MyTokenRefreshView 수정
- 에러 시 쿠키 삭제
> [BE] Fix: 비정상 logout 시 쿠키 삭제

- backend/friends/tests.py
- backend/friends/views.py
- backend/login/tests.py
- backend/login/views.py
- backend/rooms/tests.py
- backend/users/models.py
- backend/users/tests.py
- 
- is_authenticated 플래그 삭제
-
> [BE] Fix: is_authenticated flag 삭제

- frontend/src/utils/game/createGameObject.js
- frontend/src/utils/game/eventHandler.js
- frontend/src/utils/game/game.js
- #97 
- 원진님이 다 해주신 로직입니다.
- 시작 위치는 랜덤으로 시작하도록 했습니다.
-
> [Feat] 게임 로직 추가

- frontend/src/component/contents/FriendWaitListItem.js
- frontend/src/pages/Friends.js
- frontend/src/utils/Fetch.js
- #128 #129  
- Fetch - patch 매개변수 returnResponse 추가, 에러 객체 throw 추가
- 친구 수락, 삭제 후 해당 엘리먼트 삭제
> [Fix] fetch patch 요청 리턴 수정, 친구 페이지 모달 버튼 이벤트 수정

- backend/login/views.py
- backend/rooms/views.py
- backend/users/views.py
- refresh token view 수정
- room api swagger 수정
- 토큰이 유효할때 토큰의 유저정보가 db에서 찾을 수 없을 때 쿠키를 지우고 로그아웃하게 변경
- ball color string -> int
-
> 143 be fix refresh token check fix

- frontend/src/component/contents/GameRoomInfo.js
- frontend/src/index.js
- frontend/src/pages/Friends.js
- frontend/src/pages/Login.js
- frontend/src/pages/game/JoinRoom.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/scss/colors.scss
- frontend/src/scss/variables.scss
- frontend/src/utils/TokenManager.js
- #123 
- api 요청으로 받아온 정보를 map에 저장하고 모달 버튼 클릭 시 동적으로 내용 바꾸는 방식으로 구현했습니다
- 로그인 페이지에서 새로고침 시 토큰 재발급 요청 안가도록 조건문 추가
- 토큰 재발급 실패 시 로그인 페이지로 이동
- 맵 이름은 임의로 파일 명으로 했는데 방 생성 요청 보낼 때도 현재 아예 맵 이름으로 요청 보내는 건 어떨까요?
> [Feat] 게임 방 정보 모달

- frontend/src/pages/Friends.js
- frontend/src/pages/Login.js
- frontend/src/pages/Profile.js
- frontend/src/pages/game/CreateRoom.js
- frontend/src/pages/game/JoinRoom.js
- frontend/src/utils/ToastHandler.js
- frontend/src/utils/TokenManager.js
- frontend/src/utils/router.js
- #154 
- ErrorHandler가 토스트 띄우는데만 사용되어서 클래스명을 ToastHandler 로 수정했습니다
-
> [Refactor] ErrorHandler 클래스명 변경

- backend/game/consumers.py
- backend/game/models.py
- backend/game/modules.py
- backend/rooms/models.py
- backend/users/serializers.py
> 160 be 1vs1 consumer

- frontend/src/utils/Fetch.js
- frontend/vite.config.js
- #126 
- base url을 env로 관리합니다
- vite envDir 설정 추가했습니다
- 환경변수 추가 시 VITE_ 접두사 필요합니다
-
> [Feat] env 추가

- backend/game/consumers.py
- backend/game/modules.py
- backend/rooms/consumers.py
- backend/rooms/routing.py
- 1vs1 consumer 구현
- game consumer result data 수정
- room consumer url 추가
-
> [BE]fix: game consumer result fix

- frontend/src/utils/game/game.js
- #167 
- 공 히트한 순간동안 속도를 3으로 올립니다.
- 패들 히트 박스 범위를 줄여서 패들에 전보다 더 가까이 히트됩니다.
-
> [Fix] 공 히트 시 속도 수정

- .gitignore
- backend/Dockerfile
- backend/backend/asgi.py
- backend/backend/middleware.py
- backend/backend/settings.py
- backend/cmd.sh
- backend/game/consumers.py
- backend/game/modules.py
- backend/requirements.txt
- backend/rooms/consumers.py
- backend/rooms/routing.py
- backend/rooms/tests.py
- nginx/server.conf
- consumer connection test까지 완료
- daphne 설정 추가
- redis 추가
- consumer connection + test까지는 완료 되었고 기능 추가하면서 마무리 예정
- django 서버 자체는 비동기 연결을 지원을 안해서 daphne서버로 구동을 해야됨 그래서 daphne app이 최우선적으로 실행이 되서
asgi.py과 우선적으로 호출이 되는데 이때 model이 로딩이 안되서 이때 jwt middleware에서 사용하는 db접근하는 메서드는 db를 동적으로 설정해야됨 그래서 이 부분에 해당하는 코드 일부 수정
- runserver 대신 daphne으로 서버를 실행하는데 이 때문인지 프론트랑 연결이 아예안됨 main 합치고 테스트 요망
- channel layer에 사용하는 redis 서버 패키지 및 setting추가, consumer 작업하면서 channel layer관련 기능 추가시 필요한 기능이나 설정 추가 예정 (docker file에 redis 서버 구동 등등)
- 일단 merge는 하지말고 진행상황 보고 느낌으로 pr쓴거라 추후에 협의사항도 있어서 일단 변경 사항만 우선적으로 봐주세요
> consumer test 수정 및 redis, daphne 추가중

- backend/backend/asgi.py
- backend/backend/middleware.py
- backend/game/consumers.py
- backend/login/consumers.py
- backend/login/routing.py
- backend/login/tests.py
- backend/rooms/consumers.py
- backend/rooms/tests.py
- backend/users/models.py
- room consumer 마무리 및 테스트 완료
- login consumer 추가 및 테스트 완료
- 기타 주석 삭제 및 game consumer 오타 수정
- room consumer 완료했습니다
- login consumer 추가로 is_active관리가 가능해졌습니다
- 현재 is_active가 default로 true로 되어있는데 테스트를 위해 프런트랑 소켓 연결후에 db에 있는 default값 변경 필요합니다
- login테스트에 있는 본인 메일 스팸 메일 많이 받고 싶지 않으면 변경해주세용
> [BE]feat: room, login consumer add, test complete

- backend/backend/asgi.py
- backend/backend/middleware.py
- backend/login/consumers.py
- backend/login/tests.py
- JWT middleware 대공사
- 일단 consumer에서 accept는 확정적으로 받고 그 후에 메세지를 받아서 jwt토큰 처리
-
> [BE]Fix: Jwtmiddleware fix

- backend/friends/models.py
- backend/friends/tests.py
- backend/friends/views.py
- #171 
- 바뀐 http status code에 맞춰서 view 및 test 수정함
- login, friend, users 앱 테스트 모두 통과했습니다.
> [Test] http status 수정

- backend/Dockerfile
- backend/cmd.sh
- redis install dockerfile 추가
- redis server 실행 명령어 추가 
- 
-
> [BE] redis install

- frontend/src/utils/SocketManager.js
- frontend/src/utils/TokenManager.js
- #179 
- SocketManger class 구현
- 토큰 저장, 삭제 시 setOnline, setOffline 호출
-
> [Feat] 로그인 소켓 연결

- backend/login/consumers.py
- backend/login/tests.py
- backend/rooms/consumers.py
- backend/rooms/tests.py
- Login consumer response 형식 수정 (login -> access)
- Room consumer jwt인증 방식 수정 (메세지 인증)
- Room consumer 방 인원 정보 형식 수정 (table 전부 보내기)
- 
-
> [BE]fix: room, login consumer fix

- backend/login/tests.py
> [Test] login test 수정

- backend/rooms/views.py
- 
- create room response에 id 추가
-
> [BE]fix:create room response fix

- backend/rooms/consumers.py
- 
- response -> room name 추가
- disconnect시 user 정보 다시 전송 추가
-
> [BE]fix: room send_json fix

- backend/backend/settings.py
- backend/rooms/consumers.py
- backend/rooms/routing.py
- backend/rooms/views.py
- #189 
- 토너먼트 대기실 consumer 구현
- normal room 상속받아서 tounament room 만듦
- 테스트 아직 안 함
> [BE] [Feat] tournament room

- backend/game/modules.py
- backend/game/tests.py
- game module 부등호 잘못된것 수정
- random 방향으로 변경
- 
-
> [BE]fix: game module error fix

- backend/backend/settings.py
- backend/rooms/consumers.py
- backend/rooms/routing.py
- backend/rooms/tests.py
- backend/rooms/views.py
- #189 
- 대기실 대거 수정함
- 2명 대기실만 구현 및 테스트 완료, 4명 대기실은 구현 중
> [BE] [Fix] 대기실 대거 수정

- backend/rooms/consumers.py
> [BE]fix: add image path in consumer response

- backend/rooms/consumers.py
- #189 
- 대기실에 유저 추가할 때 로직 수정
- 같은 유저가 대기실에 중복 입장하려 하면 return
- 주석에서 '방' -> '대기실' 로 용어 통일했습니다.
> [BE] Fix: 대기실 중복 입장 불가

- frontend/src/pages/game/JoinRoom.js
- frontend/src/pages/game/WaitingRoom.js
- #204 
- 수정 사항 커밋을 하고 푸쉬를 안한채로 머지해버렸습니다..😅
- approve 하고 바로 머지해주셔도 됩니다!
-
> [Fix] 게임 대기실 소켓 연결

- backend/backend/middleware.py
- backend/rooms/consumers.py
- #189 
- 대기실 입장 로직 순서 수정함
- JWT middleware 수정
-
> 189 feat tournament room

- backend/backend/middleware.py
- backend/rooms/consumers.py
- #189 
- roll back!!!!!!!!!!!!
- socket에서 anonymous user 쓰지 맙시다.
> [Fix] roll back

- backend/game/consumers.py
- backend/game/modules.py
- backend/rooms/consumers.py
- game logic 수정
- game ready 뮤택스 추가
- game 객체 삭제를 한쪽 사용자에서만 진행
- room_id대신 game_id를 따로 사용
- game 계산식 대체적으로 수정
-
> [BE]fix: game logic refactor

- backend/game/consumers.py
- backend/game/modules.py
- backend/game/routing.py
- backend/game/tests.py
- backend/rooms/consumers.py
- backend/rooms/routing.py
- #212 
- 코드 수정 없이 포맷만 개선했습니다.
-
> [Chore] fixed format

- backend/game/consumers.py
- backend/game/modules.py
- backend/users/tests.py
- game consumer response 수정
- response에서 user객체를 보내는 부분에서 user.nickname으로 변경
- "error": "message" 에서 "type": "error"로 변경
- game_data에서 nick추가
- consumer modules 함수 변수 명시 변경
-
> [BE]fix: game consumer response fix

- frontend/src/pages/game/PlayGame.js
- frontend/src/utils/Router.js
- frontend/src/utils/game/GameManager.js
- frontend/src/utils/game/eventHandler/localEventHandler.js
- frontend/src/utils/game/eventHandler/multiEventHandler.js
- frontend/src/utils/game/localGame.js
- frontend/src/utils/game/render/rendering.js
- frontend/src/utils/game/render/resizeRendererToDisplaySize.js
- frontend/src/utils/game/utils/checkPaddleHit.js
- frontend/src/utils/game/utils/hitChangeColor.js
- frontend/src/utils/game/utils/localGameStartSetting.js
- #213 
- 상대방이 나간 경우, 새로고침 한 경우, 이미 꽉 찬 방에 진입하는 경우 game페이지로 이동시키고 토스트 띄웁니다.
- 상대가 나간 경우에는 'Opponent Exit'
- 새로고침한 본인, 이미 꽉 찬 방 진입하는 사람 'Game Error. Please try again later.' 입니다.
-
> [Feat] 게임 소켓 에러 처리

- backend/game/consumers.py
- backend/game/models.py
- backend/game/serializers.py
- backend/users/serializers.py
- backend/users/tests.py
- game result model 대공사
- winner, player1, player2의 username을 정적으로 저장하는 대신 user foreignkey 사용해서 동적으로 관리
- 이에 따른 test 파일 전면 수정
-
> [BE]fix:game result model, test fix"

- backend/backend/middleware.py
- backend/game/consumers.py
- backend/game/modules.py
- middleware 주석 삭제
- 게임 로직 변경
- 프로필에 게임 결과 반영
- 게임 패들 범위 상향, 공 속도 비율 증가
- 프로필 db 게임 결과 반영
-
> 224 fix game login 객체 관리 수정

- frontend/src/component/PageComponent.js
- frontend/src/component/contents/BattleHistory.js
- frontend/src/component/contents/GameRoomInfo.js
- frontend/src/pages/Profile.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/scss/colors.scss
- frontend/src/scss/variables.scss
- frontend/src/utils/Router.js
- #217 
- 프로필 페이지 배틀 히스토리 테이블 추가했습니다
- 본인 아이디에는 밝은 색상 적용했습니다
- 프로필 이미지 비율도 수정했습니다
-
> [Feat] 프로필 배틀 히스토리 조회

- backend/rooms/consumers.py
- backend/rooms/tests.py
- tournament 게임 대기실 response 수정
- 
-
> [BE] tournament 게임 대기실 수정

- frontend/src/index.html
- frontend/src/pages/game/PlayGame.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/utils/Router.js
- frontend/src/utils/game/GameManager.js
- #222 
- 멀티 소켓에서 버튼 클릭 이벤트 중첩으로 레디 여러번 보내는 문제 수정
- canvas를 index.html에서 game/play 페이지에서 렌더하는 방식으로 수정
- Router에서 app의 클래스 리스트 조건부 수정
-
> [Fix] 게임 플레이 페이지 에러 처리

- backend/game/consumers.py
- backend/game/modules.py
- backend/game/routing.py
- backend/rooms/consumers.py
- backend/rooms/tests.py
- #212 
- tournament game consumer 추가함
- 아직 작업 중입니다
> [Feat] tournament game consumer 추가

- frontend/src/component/PageComponent.js
- frontend/src/pages/game/PlayGame.js
- frontend/src/utils/Router.js
- frontend/src/utils/game/GameManager.js
- #228
- 소켓 메세지 받을 때 타입 에러가 추가되면서 수정했습니다.
- dispose에서 객체 존재 여부 확인하는 조건문 추가했습니다.
-
> [Fix] 게임 소켓 에러메세지 처리 수정

- frontend/src/pages/Friends.js
- frontend/src/pages/Login.js
- frontend/src/pages/Profile.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/scss/styles.scss
- frontend/src/utils/Fetch.js
- frontend/src/utils/TokenManager.js
- #221 
- Fetch 에러 시 Error 객체 throw 하도록 수정
- Fetch.patch 응답 상태코드와 함께 보내는 것으로 수정
-
> [Fix] Fetch 응답 수정

- backend/game/routing.py
- backend/game/tests.py
- backend/rooms/consumers.py
- backend/rooms/tests.py
- tournament room consumer 수정
- tournament room test, tournament game test 수정 사항 반영
- tournament game routing 수정
- game result game_mode추가에 따라 room consumer, game test 수정
- semi final consumer에 game_id 2가지 받도록 routing 수정
- room consumer에서 4명이 다 들어와서 방이 사라졌을 경우 접속 중이던 소켓 예외 처리 + 이에 대한 room_number 추가
- tournament room consumer test에서 또 bind error 속출로 인해 대공사
-
> [BE]fix: room consumer 수정사항 반영

- backend/backend/settings.py
- backend/cmd.sh
- backend/game/consumers.py
- backend/game/modules.py
- backend/game/routing.py
- backend/game/tests.py
- backend/requirements.txt
- backend/rooms/consumers.py
- backend/rooms/tests.py
- docker-compose.yml
- postgre db 연결
- postgre db 연결한 부분 주석 처리해서 올렸습니다. 테스트했을때 돌아가는데 컨테이너로 띄운거라 백엔드 자체테스트에서 안돌아가서 마지막에 주석 풀고 연결할 예정
- postgre db쓰면서 패키지 추가함 (requirement.txt)
- 그외에는 backend 브랜트 업데이트 내용 main에 merge하는것 입니다
-
> 247 feat postgre db 연결

- backend/game/consumers.py
- backend/game/modules.py
- backend/game/tests.py
- is_final_user 추가
- winner1, winner2에서 is_final_user (final 게임 출전 여부)로 변경
-
> [BE]fix: semi final consumer response fix

- backend/game/consumers.py
- backend/game/modules.py
- backend/game/tests.py
- semi final consumer response data 수정
- 
-
> [BE]fix:semi consumer response fix

- frontend/src/component/button/LoginPageButtons.js
- frontend/src/component/form/EmailCodeForm.js
- frontend/src/component/form/LoginForm.js
- frontend/src/component/form/RegisterForm.js
- frontend/src/component/form/RegisterFormItem.js
- frontend/src/pages/Login.js
- frontend/src/utils/SocketManager.js
- #254 
- 웹 소켓 베이스 url 수정했습니다
- 42로그인 베이스 url도 env로 불러옵니다
- 로그인 페이지에서 warning 해결
- 로그인 form 태그 추가
- input에 autocomplete 추가
-
> [CHORE] 웹 소켓 url env로 분리

- backend/friends/tests.py
- backend/friends/views.py
> [BE]fix: friend response fix

- backend/login/utils.py
> [Chore] 메일 인증 임시 제거

- backend/game/consumers.py
- backend/game/modules.py
- backend/game/tests.py
- backend/rooms/consumers.py
> [Fix] game consumer time out add

- backend/game/consumers.py
- backend/game/tests.py
- time out method 수정했습니다
- 본인이 ready버튼을 누른 후 10초 후에 상대방이 disconnect 상태거나 미접속일경우 error 메세지 보냄
-
> [BE]fix: game consumer timeout method fix

- backend/game/consumers.py
- backend/game/tests.py
- frontend/.env
> [BE]fix:game consumer timeout fix

- .gitignore
- frontend/.env
- frontend/src/component/contents/BattleHistory.js
- frontend/src/pages/game/Game.js
- frontend/src/pages/game/PlayGame.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/utils/Router.js
- frontend/src/utils/SocketManager.js
- #268 
- 게임 페이지에서 대기실로 뒤로 갔을 때 룸소켓이 재연결 두번 되는 에러가 있어서 `/game`으로 이동시켰습니다
- 프론트엔드 env가 올라가 있어서 삭제하고 gitignore 에 추가했습니다. env 파일 다시 확인해주세요!
-
> [Fix] 대기실 소켓 에러

- backend/login/serializers.py
- backend/login/views.py
- #277 
- is_active 수동 변경하는 부분 모두 삭제 (이제는 소켓으로 처리)
- refresh token 재발급 성공 시 무조건 is_active=True로 변경
- 주석 정리
- 이메일 로그인 시 중복 아이디 unique 필드로 막음 (랜덤 문자열 생성X)
-
> [Fix] user management errors

- frontend/src/component/button/LoginPageButtons.js
- frontend/src/component/modal/ModalComponent.js
- frontend/src/pages/Login.js
- frontend/src/pages/Profile.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/scss/styles.scss
- frontend/src/utils/SocketManager.js
- #274 
- 프로필 페이지 프로필 이미지 변경 버튼 만들어달라는 요청이 있어서 호버 시 포인터, 보더 색상 변경 적용으로 대체했습니다
- 대기실 나가기 버튼 추가했습니다. `/join`으로 이동하려고 했는데 popstate 이벤트가 제대로 지워지지 않는지 한 번 더 뒤로가기 했을 때 토스트가 또 떠서 그냥 `history.back()`으로 처리했습니다.
- 로그인 화면에서 엔터 누르면 새로고침 되는 문제가 있어서 submit이벤트로 모두 관리하고 2fa 모달 show, hide 시 이벤트 리스너 등록, 해제하도록 했습니다
> [Design] UI 피드백 반영 및 로그인 화면 버그 수정

- frontend/src/index.js
- frontend/src/pages/game/PlayGame.js
- #278 
- url 직접접근 막기
- 게임 종료 시 게임페이지로 이동
-
> [Fix] url 직접접근 막기 및 게임 페이지 수정

- backend/game/consumers.py
- frontend/src/index.js
- frontend/src/pages/Login.js
- frontend/src/pages/game/CreateRoom.js
- frontend/src/pages/game/PlayGame.js
- frontend/src/pages/game/WaitingRoom.js
- frontend/src/utils/SocketManager.js
- 테스트 에러 고침
- backend
- timeout 수정 및 예외 처리 추가
- frontend
- url 직접 접근 수정
- 로그인 버튼 위치 수정
- 소켓 페이지에서 다른 페이지로 이동 전 replace url 
-
> [Fix] tournament test

- backend/backend/settings.py
- backend/game/consumers.py
- docker-compose.yml
- tournament consumer final game timeout add
- postgre 추가 (주석 해제)
- 
-
> [BE]fix: tournament conusmer fix, postgre 주석 해제

- frontend/src/utils/Router.js
- frontend/src/utils/SocketManager.js
- #288 
- 뒤로가기 할 때 document title이 렌더링된 페이지로 안보이는 경우가 있어 렌더링 전 초기화해주었습니다
- 현재 대기실에서 back 버튼 누르면 소켓을 끊고 history.back()을 하는데 로컬 플레이 popstate 이벤트 추가한 부분으로 가서 에러가 나고 있는데 어떻게 고쳐야 할지 생각이 나지 않아 일단 주석 처리 해두었습니다🥲 로컬 플레이도 popstate 꼭 처리해야할까요? 그리고 로컬 플레이에서 뒤로 갔을 때 타이머 해제가 잘 안되는 것 같아요. 일단 pr만 올려둡니다!
> [Fix] 프론트 에러

- backend/cmd.sh
- backend/game/modules.py
- docker-compose.yml
- postgres/Dockerfile
- 게임 로직 수정:  최대 점수 5점 내기로 수정, 게임 시작 시 대기 시간은 놀랍게도 구현이 되어있었음
- postgre docker file 생성 및 환경 변수 분리
- super user 생성 명령 주석 처리
- database_url 환경변수 backend .env로 이동
- 
-
> 305 fix backend 수정 사항

- frontend/src/component/card/FriendInfoCard.js
- frontend/src/component/form/CreateRoomForm.js
- frontend/src/pages/game/CreateRoom.js
- frontend/src/pages/game/PlayGame.js
- frontend/src/utils/game/GameManager.js
- frontend/src/utils/game/localGame.js
- #303 
- 게임 생성 시 기본 설정 추가했습니다.(제목은 현재 시간 ms 뒤에 4자리 잘라서 붙입니다)
- 저번에 고쳐주신 친구카드 히스토리 모달 부분 추가해놨습니다.
- 로컬 게임에서 점수 나면 1초간 멈춥니다.
-
> [Fix] 프론트 수정사항

- backend/friends/models.py
- backend/friends/views.py
- backend/game/consumers.py
- backend/login/consumers.py
- backend/login/views.py
- backend/rooms/views.py
- backend/users/views.py
- #307 
- 모든 view와 consumer의 exception 처리 부분 수정
- try에 대해 발생하는 모든 exception을 general하게 다 받도록 함
> [Fix] exception handling

- backend/game/consumers.py
- backend/game/modules.py
- backend/rooms/consumers.py
- 중복 로그인 한 경우 방에 들어가려 했을 때 방이 없어지는 버그 수정
- 게임 중 중복 로그인하여 닉네임 변경을 했을 때 게임이 안 멈추는 버그 수정
- 
- 일단 변경 내용만 확인하고 테스트 후에 merge해주세용
> 312 fix duplicate login

- frontend/src/component/form/CreateRoomForm.js
- frontend/src/pages/game/PlayGame.js
- #310
- 멀티게임에도 점수 난 직후 scoring 추가했습니다.
- createRoom에서 타이틀 기본값이 come 보다는 room이 나은 것 같아서 수정했습니다. 
-
> [Feat] 멀티게임 점수 딴 직후 화면 요소 추가

- backend/backend/settings.py
> [Chore] 장고 setting 변경

- backend/friends/views.py
> [Fix] 친구 검색 시와 신청 시 닉네임이 다를 경우

- backend/login/views.py
- frontend/src/index.html
- frontend/vite.config.js
- 
- 프론트에서 http 리소스 받는 부분에서 에러 나서 수정
- vite.config https 삭제
- index.html meta 태그 추가
- 프론트 친구 삭제 버튼 왼쪽으로 옮김
- 툴팁 문제로 버튼 위치 수정했습니다. 나중에 고쳐볼게요..
- 백엔드 이메일 로그인 서버 에러 수정
-
> [FIX] frontend 설정 추가 및 backend 이메일 로그인 수정

- README.md
- #320 
- index 추가
- tech stack 추가
- page 추가
-
> [Docs] readme 업데이트
